package autogenerated_sim;

public class Functions {

public static int calculate_high_grid_square(TreeMap chemomap)
{
	return 0;
}
	
    
public static double calculate_angle_from_direction(int direction)
{
	return 0;
}
	
    
public static int collision_check(Double2D cell_loc, Tracking_Stats tracking, int cell_id, String cellType)
{
	return 0;
}
	
    
public static boolean detect_cell_bind(Double2D loc, String cellType)
{
	return false;
}
	
    
public static double measure_chemokine_expression(Double2D loc, TreeMap chemomap)
{
	return 0;
}
	
    
public static Double2D calculateNewPosition(Double2D cell_loc, double angle_to_move, double movement_interval)
{
	return new Double2D();
}
	
    
public static int set_ltin_contact_time()
{
	return 0;
}
	
    
public static double probability_responds_to_chemokine(Double2D cell_loc, double totalchemolevels, TreeMap chemomap)
{
	return 0;
}
	
    
public static double calculate_probability_adhesion(int contactedCell_ID)
{
	return 0;
}
	
    
public static int set_lti_contact_time()
{
	return 0;
}
	
    
public static double set_cell_speed(double random_num, double lower_bound, double upper_bound)
{
	return 0;
}
	
    
public static double avoidCellCollision(Double2D cell_loc, double distanceToMove, int contactedCell_ID)
{
	return 0;
}
	
    
public static boolean check_valid_location_on_grid(Double2D cell_loc)
{
	return false;
}
	
    

}

