package autogenerated_sim;

import roboCalcAPI.Stages;
import roboCalcAPI.State;
import roboCalcAPI.StateMachine;
import roboCalcAPI.Timer;
import roboCalcAPI.Transition;

public class LTi_State_Machine extends StateMachine
{
	
	// Clocks and variable list:
	public Timer T;
	public LTiStep R_LTiStep;
	public LTiController C_LTiController;
public boolean move_finished;
public boolean adhered;
public int contactedCell_ID;
public double probabilityOfAdhesion;
public double chemokine_response_probability;
public double distanceToMove;
public double distanceMoved;
public double movement_interval;
public double pJunctionValue;

// Constructor needs to go here, and check Execute
	
public LTi_State_Machine(LTiStep R_LTiStep, LTiController C_LTiController) 
{
	super("LTi_State_Machine");
	this.R_LTiStep = R_LTiStep;  
	this.C_LTiController = C_LTiController;
						
						
		this.move_finished = false;
		this.adhered = false;
		this.contactedCell_ID = -1;
		this.probabilityOfAdhesion = 0;
		this.chemokine_response_probability = 0;
		this.distanceToMove = 0;
		this.distanceMoved = 0;
		this.movement_interval = 0;

	pJunctionValue = Mason_Sim_Main.rng.nextDouble();
	T = new Timer("T");
						
	
	// instantiate states && add substates of machine
	i0 S_LTi_State_Machine_i0 = new i0(R_LTiStep, C_LTiController, this);
	states.add(S_LTi_State_Machine_i0);
	Chemotactic S_LTi_State_Machine_Chemotactic = new Chemotactic(R_LTiStep, C_LTiController, this);
	states.add(S_LTi_State_Machine_Chemotactic);
	Non_Chemotactic S_LTi_State_Machine_Non_Chemotactic = new Non_Chemotactic(R_LTiStep, C_LTiController, this);
	states.add(S_LTi_State_Machine_Non_Chemotactic);
	p0 S_LTi_State_Machine_p0 = new p0(R_LTiStep, C_LTiController, this);
	states.add(S_LTi_State_Machine_p0);
	Adhesion_Response S_LTi_State_Machine_Adhesion_Response = new Adhesion_Response(R_LTiStep, C_LTiController, this);
	states.add(S_LTi_State_Machine_Adhesion_Response);

	t1 S_LTi_State_Machine_t1 = new t1(R_LTiStep, C_LTiController, this, S_LTi_State_Machine_Chemotactic, S_LTi_State_Machine_p0);
	S_LTi_State_Machine_Chemotactic.transitions.add(S_LTi_State_Machine_t1);
	t2 S_LTi_State_Machine_t2 = new t2(R_LTiStep, C_LTiController, this, S_LTi_State_Machine_p0, S_LTi_State_Machine_Non_Chemotactic);
	S_LTi_State_Machine_p0.transitions.add(S_LTi_State_Machine_t2);
	t3 S_LTi_State_Machine_t3 = new t3(R_LTiStep, C_LTiController, this, S_LTi_State_Machine_p0, S_LTi_State_Machine_Chemotactic);
	S_LTi_State_Machine_p0.transitions.add(S_LTi_State_Machine_t3);
	t4 S_LTi_State_Machine_t4 = new t4(R_LTiStep, C_LTiController, this, S_LTi_State_Machine_Non_Chemotactic, S_LTi_State_Machine_p0);
	S_LTi_State_Machine_Non_Chemotactic.transitions.add(S_LTi_State_Machine_t4);
	t5 S_LTi_State_Machine_t5 = new t5(R_LTiStep, C_LTiController, this, S_LTi_State_Machine_Non_Chemotactic, S_LTi_State_Machine_Adhesion_Response);
	S_LTi_State_Machine_Non_Chemotactic.transitions.add(S_LTi_State_Machine_t5);
	t6 S_LTi_State_Machine_t6 = new t6(R_LTiStep, C_LTiController, this, S_LTi_State_Machine_Chemotactic, S_LTi_State_Machine_Adhesion_Response);
	S_LTi_State_Machine_Chemotactic.transitions.add(S_LTi_State_Machine_t6);
	t0 S_LTi_State_Machine_t0 = new t0(R_LTiStep, C_LTiController, this, S_LTi_State_Machine_i0, S_LTi_State_Machine_Chemotactic);
	S_LTi_State_Machine_i0.transitions.add(S_LTi_State_Machine_t0);
	t11 S_LTi_State_Machine_t11 = new t11(R_LTiStep, C_LTiController, this, S_LTi_State_Machine_Adhesion_Response, S_LTi_State_Machine_Adhesion_Response);
	S_LTi_State_Machine_Adhesion_Response.transitions.add(S_LTi_State_Machine_t11);
	t7 S_LTi_State_Machine_t7 = new t7(R_LTiStep, C_LTiController, this, S_LTi_State_Machine_Adhesion_Response, S_LTi_State_Machine_Chemotactic);
	S_LTi_State_Machine_Adhesion_Response.transitions.add(S_LTi_State_Machine_t7);

	stage = Stages.s_Enter;
						
}
					
					

	
	public int Initial()
	{
		return 0;
	}
	
	public void Execute()
	{
		super.Execute();
		T.IncCounter();
	}
	
	// Now to build the states and any other inner state machines

public class i0 extends State 
{
	private LTiStep R_LTiStep;
	private LTiController C_LTiController;
	private LTi_State_Machine S_LTi_State_Machine;
	
	public i0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
	{
		super("i0",Stages.s_Inactive);
		this.R_LTiStep = R_LTiStep;
		this.C_LTiController = C_LTiController;
		this.S_LTi_State_Machine = S_LTi_State_Machine;
		
	}
	
}
public class Chemotactic extends State 
{
	private LTiStep R_LTiStep;
	private LTiController C_LTiController;
	private LTi_State_Machine S_LTi_State_Machine;
	
	public Chemotactic(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
	{
		super("Chemotactic",Stages.s_Inactive);
		this.R_LTiStep = R_LTiStep;
		this.C_LTiController = C_LTiController;
		this.S_LTi_State_Machine = S_LTi_State_Machine;
		
		// instantiate states && add substates of machine
		i0 Chemotactic_i0 = new i0(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Chemotactic_i0);
		Motile Chemotactic_Motile = new Motile(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Chemotactic_Motile);
		Disassociated Chemotactic_Disassociated = new Disassociated(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Chemotactic_Disassociated);
		Associated Chemotactic_Associated = new Associated(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Chemotactic_Associated);
		p0 Chemotactic_p0 = new p0(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Chemotactic_p0);
		
		t0 Chemotactic_t0 = new t0(R_LTiStep, C_LTiController, S_LTi_State_Machine, Chemotactic_Motile, Chemotactic_p0);
		Chemotactic_Motile.transitions.add(Chemotactic_t0);
		t1 Chemotactic_t1 = new t1(R_LTiStep, C_LTiController, S_LTi_State_Machine, Chemotactic_p0, Chemotactic_Disassociated);
		Chemotactic_p0.transitions.add(Chemotactic_t1);
		t2 Chemotactic_t2 = new t2(R_LTiStep, C_LTiController, S_LTi_State_Machine, Chemotactic_p0, Chemotactic_Associated);
		Chemotactic_p0.transitions.add(Chemotactic_t2);
		t7 Chemotactic_t7 = new t7(R_LTiStep, C_LTiController, S_LTi_State_Machine, Chemotactic_Motile, Chemotactic_Motile);
		Chemotactic_Motile.transitions.add(Chemotactic_t7);
		t3 Chemotactic_t3 = new t3(R_LTiStep, C_LTiController, S_LTi_State_Machine, Chemotactic_i0, Chemotactic_Motile);
		Chemotactic_i0.transitions.add(Chemotactic_t3);
	}
	public void Entry()
	{
		S_LTi_State_Machine.distanceToMove = R_LTiStep.LTiStep_LTi_Attributes.cellSpeed;
		S_LTi_State_Machine.distanceMoved = 0;
		S_LTi_State_Machine.movement_interval = 0.1;
		R_LTiStep.LTiStep_LTi_Attributes.angle_to_move = Functions.calculate_angle_from_direction(R_LTiStep.LTiStep_LTi_Attributes.high_chemokine_grid_square);
		S_LTi_State_Machine.move_finished = false;
	}
	public void Exit() 
	{
		 R_LTiStep.LTiStep_Operations.update_tracking_stats(R_LTiStep.LTiStep_LTi_Attributes.tracking, R_LTiStep.LTiStep_LTi_Attributes.cell_id, R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, S_LTi_State_Machine.distanceMoved); 
	}
	
	public class Motile extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public Motile(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("Motile",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry()
			{
				if (S_LTi_State_Machine.move_finished == false) 
				{
					if (S_LTi_State_Machine.movement_interval > S_LTi_State_Machine.distanceToMove) 
					{
						S_LTi_State_Machine.movement_interval = S_LTi_State_Machine.distanceToMove;
					}
					R_LTiStep.LTiStep_LTi_Attributes.LTi_loc = Functions.calculateNewPosition(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.angle_to_move, S_LTi_State_Machine.movement_interval);
					S_LTi_State_Machine.distanceToMove = S_LTi_State_Machine.distanceToMove - S_LTi_State_Machine.movement_interval;
					S_LTi_State_Machine.distanceMoved = S_LTi_State_Machine.distanceMoved + S_LTi_State_Machine.movement_interval;
					 R_LTiStep.LTiStep_Operations.setPositionOnTract(R_LTiStep.LTiStep_LTi_Attributes.cell_id, R_LTiStep.LTiStep_LTi_Attributes.LTi_loc); 
					if (S_LTi_State_Machine.distanceToMove == 0) 
					{
						S_LTi_State_Machine.move_finished = true;
					}
					if (Functions.check_valid_location_on_grid(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc) == true) 
					{
						S_LTi_State_Machine.contactedCell_ID = Functions.collision_check(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.tracking, R_LTiStep.LTiStep_LTi_Attributes.cell_id, "LTi");
						S_LTi_State_Machine.probabilityOfAdhesion = Functions.calculate_probability_adhesion(S_LTi_State_Machine.contactedCell_ID);
					}
					else 
					{
						 R_LTiStep.LTiStep_Operations.stop_cell_on_schedule(R_LTiStep.LTiStep_LTi_Attributes.cell_id); 
						S_LTi_State_Machine.move_finished = true;
						S_LTi_State_Machine.probabilityOfAdhesion = 0;
					}
				}
			}
			
		};
	public class Disassociated extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public Disassociated(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("Disassociated",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry()
			{
				R_LTiStep.LTiStep_LTi_Attributes.angle_to_move = Functions.avoidCellCollision(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, S_LTi_State_Machine.distanceToMove, S_LTi_State_Machine.contactedCell_ID);
				R_LTiStep.LTiStep_LTi_Attributes.LTi_loc = Functions.calculateNewPosition(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.angle_to_move, S_LTi_State_Machine.distanceToMove);
				if (Functions.check_valid_location_on_grid(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc) == true) 
				{
					 R_LTiStep.LTiStep_Operations.setPositionOnTract(R_LTiStep.LTiStep_LTi_Attributes.cell_id, R_LTiStep.LTiStep_LTi_Attributes.LTi_loc); 
				}
				else 
				{
					 R_LTiStep.LTiStep_Operations.stop_cell_on_schedule(R_LTiStep.LTiStep_LTi_Attributes.cell_id); 
				}
				S_LTi_State_Machine.distanceMoved = S_LTi_State_Machine.distanceMoved + S_LTi_State_Machine.distanceToMove;
				S_LTi_State_Machine.distanceToMove = 0;
				S_LTi_State_Machine.move_finished = true;
				S_LTi_State_Machine.contactedCell_ID = -1;
			}
			
		};
	public class Associated extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public Associated(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("Associated",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry()
			{
				S_LTi_State_Machine.adhered = true;
			}
			
		};
	public class p0 extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public p0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("p0",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry() 
			{
				S_LTi_State_Machine.pJunctionValue =  Mason_Sim_Main.rng.nextDouble();
			}
			
		};
	public class i0 extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public i0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("i0",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			
		};
		
		public int Initial()
		{
			return 0;
		}
		public void Execute()
		{
			super.Execute();
		}
	public class t0 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
				
				
			public 	t0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
					S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Chemotactic_t0", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
				// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
			}
					
				public boolean Condition() {
					if (S_LTi_State_Machine.contactedCell_ID != -1) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Chemotactic_t0 is true");
						return true;
					}
					else {
						System.out.println("Condition of transition S_LTi_State_Machine_Chemotactic_t0 is false");
						return false;
					}
				}
		};
	public class t7 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
				
				
			public 	t7(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
					S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Chemotactic_t7", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
				// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
			}
					
				public boolean Condition() {
					if (S_LTi_State_Machine.contactedCell_ID == -1 && S_LTi_State_Machine.move_finished == false) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Chemotactic_t7 is true");
						return true;
					}
					else {
						System.out.println("Condition of transition S_LTi_State_Machine_Chemotactic_t7 is false");
						return false;
					}
				}
		};
	public class t1 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public t1(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Chemotactic_t1", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
			}
			
			public boolean Condition() 
			{
				if (S_LTi_State_Machine.pJunctionValue > (0) && S_LTi_State_Machine.pJunctionValue <= (0 + (1 - S_LTi_State_Machine.probabilityOfAdhesion))) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Chemotactic_t1 is true");
						return true;
				}
				else {
					//System.out.println("Condition of transition S_LTi_State_Machine_Chemotactic_t1 is false");
					return false;
				}
			}
		};
	
	//0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion
	public class t2 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public t2(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Chemotactic_t2", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
			}
			
			public boolean Condition() 
			{
				if (S_LTi_State_Machine.pJunctionValue > (0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion) && S_LTi_State_Machine.pJunctionValue <= (0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion + (S_LTi_State_Machine.probabilityOfAdhesion))) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Chemotactic_t2 is true");
						return true;
				}
				else {
					//System.out.println("Condition of transition S_LTi_State_Machine_Chemotactic_t2 is false");
					return false;
				}
			}
		};
	
	//0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion + S_LTi_State_Machine.probabilityOfAdhesion
	//0
	public class t3 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
				
				
			public 	t3(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
					S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Chemotactic_t3", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
				// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
			}
					
		};
}
public class Non_Chemotactic extends State 
{
	private LTiStep R_LTiStep;
	private LTiController C_LTiController;
	private LTi_State_Machine S_LTi_State_Machine;
	
	public Non_Chemotactic(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
	{
		super("Non_Chemotactic",Stages.s_Inactive);
		this.R_LTiStep = R_LTiStep;
		this.C_LTiController = C_LTiController;
		this.S_LTi_State_Machine = S_LTi_State_Machine;
		
		// instantiate states && add substates of machine
		i0 Non_Chemotactic_i0 = new i0(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Non_Chemotactic_i0);
		Motile Non_Chemotactic_Motile = new Motile(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Non_Chemotactic_Motile);
		Disassociated Non_Chemotactic_Disassociated = new Disassociated(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Non_Chemotactic_Disassociated);
		Associated Non_Chemotactic_Associated = new Associated(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Non_Chemotactic_Associated);
		p0 Non_Chemotactic_p0 = new p0(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Non_Chemotactic_p0);
		
		t0 Non_Chemotactic_t0 = new t0(R_LTiStep, C_LTiController, S_LTi_State_Machine, Non_Chemotactic_Motile, Non_Chemotactic_p0);
		Non_Chemotactic_Motile.transitions.add(Non_Chemotactic_t0);
		t1 Non_Chemotactic_t1 = new t1(R_LTiStep, C_LTiController, S_LTi_State_Machine, Non_Chemotactic_p0, Non_Chemotactic_Disassociated);
		Non_Chemotactic_p0.transitions.add(Non_Chemotactic_t1);
		t2 Non_Chemotactic_t2 = new t2(R_LTiStep, C_LTiController, S_LTi_State_Machine, Non_Chemotactic_p0, Non_Chemotactic_Associated);
		Non_Chemotactic_p0.transitions.add(Non_Chemotactic_t2);
		t3 Non_Chemotactic_t3 = new t3(R_LTiStep, C_LTiController, S_LTi_State_Machine, Non_Chemotactic_Motile, Non_Chemotactic_Motile);
		Non_Chemotactic_Motile.transitions.add(Non_Chemotactic_t3);
		t4 Non_Chemotactic_t4 = new t4(R_LTiStep, C_LTiController, S_LTi_State_Machine, Non_Chemotactic_i0, Non_Chemotactic_Motile);
		Non_Chemotactic_i0.transitions.add(Non_Chemotactic_t4);
	}
	public void Entry()
	{
		S_LTi_State_Machine.distanceToMove = R_LTiStep.LTiStep_LTi_Attributes.cellSpeed;
		S_LTi_State_Machine.distanceMoved = 0;
		R_LTiStep.LTiStep_LTi_Attributes.angle_to_move = Functions.calculate_angle_from_direction(99);
		S_LTi_State_Machine.move_finished = false;
		S_LTi_State_Machine.movement_interval = 0.1;
	}
	public void Exit() 
	{
		 R_LTiStep.LTiStep_Operations.update_tracking_stats(R_LTiStep.LTiStep_LTi_Attributes.tracking, R_LTiStep.LTiStep_LTi_Attributes.cell_id, R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, S_LTi_State_Machine.distanceMoved); 
	}
	
	public class i0 extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public i0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("i0",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			
		};
		
		public int Initial()
		{
			return 0;
		}
		public void Execute()
		{
			super.Execute();
		}
	public class Motile extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public Motile(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("Motile",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry()
			{
				if (S_LTi_State_Machine.move_finished == false) 
				{
					if (S_LTi_State_Machine.movement_interval > S_LTi_State_Machine.distanceToMove) 
					{
						S_LTi_State_Machine.movement_interval = S_LTi_State_Machine.distanceToMove;
					}
					R_LTiStep.LTiStep_LTi_Attributes.LTi_loc = Functions.calculateNewPosition(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.angle_to_move, S_LTi_State_Machine.movement_interval);
					S_LTi_State_Machine.distanceToMove = S_LTi_State_Machine.distanceToMove - S_LTi_State_Machine.movement_interval;
					S_LTi_State_Machine.distanceMoved = S_LTi_State_Machine.distanceMoved + S_LTi_State_Machine.movement_interval;
					 R_LTiStep.LTiStep_Operations.setPositionOnTract(R_LTiStep.LTiStep_LTi_Attributes.cell_id, R_LTiStep.LTiStep_LTi_Attributes.LTi_loc); 
					if (S_LTi_State_Machine.distanceToMove == 0) 
					{
						S_LTi_State_Machine.move_finished = true;
					}
					if (Functions.check_valid_location_on_grid(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc) == true) 
					{
						S_LTi_State_Machine.contactedCell_ID = Functions.collision_check(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.tracking, R_LTiStep.LTiStep_LTi_Attributes.cell_id, "LTi");
						S_LTi_State_Machine.probabilityOfAdhesion = Functions.calculate_probability_adhesion(S_LTi_State_Machine.contactedCell_ID);
					}
					else 
					{
						 R_LTiStep.LTiStep_Operations.stop_cell_on_schedule(R_LTiStep.LTiStep_LTi_Attributes.cell_id); 
						S_LTi_State_Machine.move_finished = true;
						S_LTi_State_Machine.probabilityOfAdhesion = 0;
					}
				}
			}
			
		};
	public class Disassociated extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public Disassociated(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("Disassociated",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry()
			{
				R_LTiStep.LTiStep_LTi_Attributes.angle_to_move = Functions.avoidCellCollision(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, S_LTi_State_Machine.distanceToMove, S_LTi_State_Machine.contactedCell_ID);
				R_LTiStep.LTiStep_LTi_Attributes.LTi_loc = Functions.calculateNewPosition(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.angle_to_move, S_LTi_State_Machine.distanceToMove);
				if (Functions.check_valid_location_on_grid(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc) == true) 
				{
					 R_LTiStep.LTiStep_Operations.setPositionOnTract(R_LTiStep.LTiStep_LTi_Attributes.cell_id, R_LTiStep.LTiStep_LTi_Attributes.LTi_loc); 
				}
				else 
				{
					 R_LTiStep.LTiStep_Operations.stop_cell_on_schedule(R_LTiStep.LTiStep_LTi_Attributes.cell_id); 
				}
				S_LTi_State_Machine.distanceMoved = S_LTi_State_Machine.distanceMoved + S_LTi_State_Machine.distanceToMove;
				S_LTi_State_Machine.distanceToMove = 0;
				S_LTi_State_Machine.move_finished = true;
				S_LTi_State_Machine.contactedCell_ID = -1;
			}
			
		};
	public class Associated extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public Associated(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("Associated",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry()
			{
				S_LTi_State_Machine.adhered = true;
			}
			
		};
	public class p0 extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public p0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("p0",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry() 
			{
				S_LTi_State_Machine.pJunctionValue =  Mason_Sim_Main.rng.nextDouble();
			}
			
		};
	public class t4 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
				
				
			public 	t4(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
					S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Non_Chemotactic_t4", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
				// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
			}
					
		};
	public class t0 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
				
				
			public 	t0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
					S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Non_Chemotactic_t0", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
				// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
			}
					
				public boolean Condition() {
					if (S_LTi_State_Machine.contactedCell_ID != -1) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Non_Chemotactic_t0 is true");
						return true;
					}
					else {
						System.out.println("Condition of transition S_LTi_State_Machine_Non_Chemotactic_t0 is false");
						return false;
					}
				}
		};
	public class t3 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
				
				
			public 	t3(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
					S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Non_Chemotactic_t3", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
				// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
			}
					
				public boolean Condition() {
					if (S_LTi_State_Machine.contactedCell_ID == -1 && S_LTi_State_Machine.move_finished == false) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Non_Chemotactic_t3 is true");
						return true;
					}
					else {
						System.out.println("Condition of transition S_LTi_State_Machine_Non_Chemotactic_t3 is false");
						return false;
					}
				}
		};
	public class t1 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public t1(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Non_Chemotactic_t1", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
			}
			
			public boolean Condition() 
			{
				if (S_LTi_State_Machine.pJunctionValue > (0) && S_LTi_State_Machine.pJunctionValue <= (0 + (1 - S_LTi_State_Machine.probabilityOfAdhesion))) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Non_Chemotactic_t1 is true");
						return true;
				}
				else {
					//System.out.println("Condition of transition S_LTi_State_Machine_Non_Chemotactic_t1 is false");
					return false;
				}
			}
		};
	
	//0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion
	public class t2 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public t2(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Non_Chemotactic_t2", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
			}
			
			public boolean Condition() 
			{
				if (S_LTi_State_Machine.pJunctionValue > (0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion) && S_LTi_State_Machine.pJunctionValue <= (0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion + (S_LTi_State_Machine.probabilityOfAdhesion))) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Non_Chemotactic_t2 is true");
						return true;
				}
				else {
					//System.out.println("Condition of transition S_LTi_State_Machine_Non_Chemotactic_t2 is false");
					return false;
				}
			}
		};
	
	//0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion + S_LTi_State_Machine.probabilityOfAdhesion
	//0
}
public class p0 extends State 
{
	private LTiStep R_LTiStep;
	private LTiController C_LTiController;
	private LTi_State_Machine S_LTi_State_Machine;
	
	public p0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
	{
		super("p0",Stages.s_Inactive);
		this.R_LTiStep = R_LTiStep;
		this.C_LTiController = C_LTiController;
		this.S_LTi_State_Machine = S_LTi_State_Machine;
		
	}
	public void Entry() 
	{
		S_LTi_State_Machine.pJunctionValue =  Mason_Sim_Main.rng.nextDouble();
	}
	
}
public class Adhesion_Response extends State 
{
	private LTiStep R_LTiStep;
	private LTiController C_LTiController;
	private LTi_State_Machine S_LTi_State_Machine;
	
	public Adhesion_Response(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
	{
		super("Adhesion_Response",Stages.s_Inactive);
		this.R_LTiStep = R_LTiStep;
		this.C_LTiController = C_LTiController;
		this.S_LTi_State_Machine = S_LTi_State_Machine;
		
		// instantiate states && add substates of machine
		i0 Adhesion_Response_i0 = new i0(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Adhesion_Response_i0);
		Adhered Adhesion_Response_Adhered = new Adhered(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Adhesion_Response_Adhered);
		Disassociated Adhesion_Response_Disassociated = new Disassociated(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Adhesion_Response_Disassociated);
		p0 Adhesion_Response_p0 = new p0(R_LTiStep, C_LTiController, S_LTi_State_Machine);
		states.add(Adhesion_Response_p0);
		
		t0 Adhesion_Response_t0 = new t0(R_LTiStep, C_LTiController, S_LTi_State_Machine, Adhesion_Response_Adhered, Adhesion_Response_p0);
		Adhesion_Response_Adhered.transitions.add(Adhesion_Response_t0);
		t1 Adhesion_Response_t1 = new t1(R_LTiStep, C_LTiController, S_LTi_State_Machine, Adhesion_Response_p0, Adhesion_Response_Disassociated);
		Adhesion_Response_p0.transitions.add(Adhesion_Response_t1);
		t2 Adhesion_Response_t2 = new t2(R_LTiStep, C_LTiController, S_LTi_State_Machine, Adhesion_Response_p0, Adhesion_Response_Adhered);
		Adhesion_Response_p0.transitions.add(Adhesion_Response_t2);
		t3 Adhesion_Response_t3 = new t3(R_LTiStep, C_LTiController, S_LTi_State_Machine, Adhesion_Response_i0, Adhesion_Response_Adhered);
		Adhesion_Response_i0.transitions.add(Adhesion_Response_t3);
	}
	public void Entry()
	{
		S_LTi_State_Machine.distanceToMove = R_LTiStep.LTiStep_LTi_Attributes.cellSpeed;
		S_LTi_State_Machine.distanceMoved = 0;
		R_LTiStep.LTiStep_LTi_Attributes.angle_to_move = Functions.calculate_angle_from_direction(R_LTiStep.LTiStep_LTi_Attributes.high_chemokine_grid_square);
		S_LTi_State_Machine.move_finished = false;
	}
	public void Exit() 
	{
		 R_LTiStep.LTiStep_Operations.update_tracking_stats(R_LTiStep.LTiStep_LTi_Attributes.tracking, R_LTiStep.LTiStep_LTi_Attributes.cell_id, R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, S_LTi_State_Machine.distanceMoved); 
	}
	
	public class Adhered extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public Adhered(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("Adhered",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry()
			{
				if (S_LTi_State_Machine.move_finished == false) 
				{
					S_LTi_State_Machine.probabilityOfAdhesion = Functions.calculate_probability_adhesion(S_LTi_State_Machine.contactedCell_ID);
				}
			}
			
		};
	public class Disassociated extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public Disassociated(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("Disassociated",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry()
			{
				R_LTiStep.LTiStep_LTi_Attributes.angle_to_move = Functions.avoidCellCollision(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, S_LTi_State_Machine.distanceToMove, S_LTi_State_Machine.contactedCell_ID);
				R_LTiStep.LTiStep_LTi_Attributes.LTi_loc = Functions.calculateNewPosition(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.angle_to_move, S_LTi_State_Machine.distanceToMove);
				if (Functions.check_valid_location_on_grid(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc) == true) 
				{
					 R_LTiStep.LTiStep_Operations.setPositionOnTract(R_LTiStep.LTiStep_LTi_Attributes.cell_id, R_LTiStep.LTiStep_LTi_Attributes.LTi_loc); 
				}
				else 
				{
					 R_LTiStep.LTiStep_Operations.stop_cell_on_schedule(R_LTiStep.LTiStep_LTi_Attributes.cell_id); 
				}
				S_LTi_State_Machine.distanceMoved = S_LTi_State_Machine.distanceMoved + S_LTi_State_Machine.distanceToMove;
				S_LTi_State_Machine.distanceToMove = 0;
				S_LTi_State_Machine.move_finished = true;
				S_LTi_State_Machine.contactedCell_ID = -1;
				S_LTi_State_Machine.adhered = false;
			}
			
		};
	public class p0 extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public p0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("p0",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			public void Entry() 
			{
				S_LTi_State_Machine.pJunctionValue =  Mason_Sim_Main.rng.nextDouble();
			}
			
		};
	public class i0 extends State 
		{
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public i0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine)
			{
				super("i0",Stages.s_Inactive);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
			}
			
		};
		
		public int Initial()
		{
			return 0;
		}
		public void Execute()
		{
			super.Execute();
		}
	public class t0 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
				
				
			public 	t0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
					S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Adhesion_Response_t0", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
				// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
			}
					
				public boolean Condition() {
					if (S_LTi_State_Machine.move_finished == false) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Adhesion_Response_t0 is true");
						return true;
					}
					else {
						System.out.println("Condition of transition S_LTi_State_Machine_Adhesion_Response_t0 is false");
						return false;
					}
				}
		};
	public class t1 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public t1(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Adhesion_Response_t1", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
			}
			
			public boolean Condition() 
			{
				if (S_LTi_State_Machine.pJunctionValue > (0) && S_LTi_State_Machine.pJunctionValue <= (0 + (1 - S_LTi_State_Machine.probabilityOfAdhesion))) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Adhesion_Response_t1 is true");
						return true;
				}
				else {
					//System.out.println("Condition of transition S_LTi_State_Machine_Adhesion_Response_t1 is false");
					return false;
				}
			}
		};
	
	//0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion
	public class t2 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
			
			public t2(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Adhesion_Response_t2", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
			}
			
			public boolean Condition() 
			{
				if (S_LTi_State_Machine.pJunctionValue > (0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion) && S_LTi_State_Machine.pJunctionValue <= (0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion + (S_LTi_State_Machine.probabilityOfAdhesion))) {
						//System.out.println("Condition of transition S_LTi_State_Machine_Adhesion_Response_t2 is true");
						return true;
				}
				else {
					//System.out.println("Condition of transition S_LTi_State_Machine_Adhesion_Response_t2 is false");
					return false;
				}
			}
			public void Action() {
				S_LTi_State_Machine.move_finished = true;
			}
		};
	
	//0 + 1 - S_LTi_State_Machine.probabilityOfAdhesion + S_LTi_State_Machine.probabilityOfAdhesion
	//0
	public class t3 extends Transition {
			private LTiStep R_LTiStep;
			private LTiController C_LTiController;
			private LTi_State_Machine S_LTi_State_Machine;
				
				
			public 	t3(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
					S_LTi_State_Machine, State src, State tgt)
			{
				super("S_LTi_State_Machine_Adhesion_Response_t3", src, tgt);
				this.R_LTiStep = R_LTiStep;
				this.C_LTiController = C_LTiController;
				this.S_LTi_State_Machine = S_LTi_State_Machine;
				
				// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
			}
					
		};
}

public class t0 extends Transition {
		private LTiStep R_LTiStep;
		private LTiController C_LTiController;
		private LTi_State_Machine S_LTi_State_Machine;
			
			
		public 	t0(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
				S_LTi_State_Machine, State src, State tgt)
		{
			super("S_LTi_State_Machine_t0", src, tgt);
			this.R_LTiStep = R_LTiStep;
			this.C_LTiController = C_LTiController;
			this.S_LTi_State_Machine = S_LTi_State_Machine;
			
			// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
		}
				
			public void Action() {
				S_LTi_State_Machine.T.SetCounter(0);
				//System.out.println("Resetting Clock T");
			}
	};
public class t1 extends Transition {
		private LTiStep R_LTiStep;
		private LTiController C_LTiController;
		private LTi_State_Machine S_LTi_State_Machine;
			
			
		public 	t1(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
				S_LTi_State_Machine, State src, State tgt)
		{
			super("S_LTi_State_Machine_t1", src, tgt);
			this.R_LTiStep = R_LTiStep;
			this.C_LTiController = C_LTiController;
			this.S_LTi_State_Machine = S_LTi_State_Machine;
			
			// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
		}
				
			public boolean Condition() {
				if (S_LTi_State_Machine.contactedCell_ID == -1 && S_LTi_State_Machine.T.GetCounter() > 0) {
					//System.out.println("Condition of transition S_LTi_State_Machine_t1 is true");
					return true;
				}
				else {
					System.out.println("Condition of transition S_LTi_State_Machine_t1 is false");
					return false;
				}
			}
			public void Action() {
				R_LTiStep.LTiStep_LTi_Attributes.totalchemoLevels = Functions.measure_chemokine_expression(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.chemomap);
				if (R_LTiStep.LTiStep_LTi_Attributes.totalchemoLevels > 0) 
				{
					R_LTiStep.LTiStep_LTi_Attributes.high_chemokine_grid_square = Functions.calculate_high_grid_square(R_LTiStep.LTiStep_LTi_Attributes.chemomap);
				}
				else 
				{
					R_LTiStep.LTiStep_LTi_Attributes.high_chemokine_grid_square = -1;
				}
				S_LTi_State_Machine.chemokine_response_probability = Functions.probability_responds_to_chemokine(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.totalchemoLevels, R_LTiStep.LTiStep_LTi_Attributes.chemomap);
				S_LTi_State_Machine.T.SetCounter(0);
				//System.out.println("Resetting Clock T");
			}
	};
public class t6 extends Transition {
		private LTiStep R_LTiStep;
		private LTiController C_LTiController;
		private LTi_State_Machine S_LTi_State_Machine;
			
			
		public 	t6(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
				S_LTi_State_Machine, State src, State tgt)
		{
			super("S_LTi_State_Machine_t6", src, tgt);
			this.R_LTiStep = R_LTiStep;
			this.C_LTiController = C_LTiController;
			this.S_LTi_State_Machine = S_LTi_State_Machine;
			
			// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
		}
				
			public boolean Condition() {
				if (S_LTi_State_Machine.contactedCell_ID != 1 && S_LTi_State_Machine.adhered == true && S_LTi_State_Machine.T.GetCounter() > 0) {
					//System.out.println("Condition of transition S_LTi_State_Machine_t6 is true");
					return true;
				}
				else {
					System.out.println("Condition of transition S_LTi_State_Machine_t6 is false");
					return false;
				}
			}
			public void Action() {
				S_LTi_State_Machine.T.SetCounter(0);
				//System.out.println("Resetting Clock T");
			}
	};
public class t4 extends Transition {
		private LTiStep R_LTiStep;
		private LTiController C_LTiController;
		private LTi_State_Machine S_LTi_State_Machine;
			
			
		public 	t4(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
				S_LTi_State_Machine, State src, State tgt)
		{
			super("S_LTi_State_Machine_t4", src, tgt);
			this.R_LTiStep = R_LTiStep;
			this.C_LTiController = C_LTiController;
			this.S_LTi_State_Machine = S_LTi_State_Machine;
			
			// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
		}
				
			public boolean Condition() {
				if (S_LTi_State_Machine.contactedCell_ID == -1 && S_LTi_State_Machine.T.GetCounter() > 0) {
					//System.out.println("Condition of transition S_LTi_State_Machine_t4 is true");
					return true;
				}
				else {
					System.out.println("Condition of transition S_LTi_State_Machine_t4 is false");
					return false;
				}
			}
			public void Action() {
				R_LTiStep.LTiStep_LTi_Attributes.totalchemoLevels = Functions.measure_chemokine_expression(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.chemomap);
				if (R_LTiStep.LTiStep_LTi_Attributes.totalchemoLevels > 0) 
				{
					R_LTiStep.LTiStep_LTi_Attributes.high_chemokine_grid_square = Functions.calculate_high_grid_square(R_LTiStep.LTiStep_LTi_Attributes.chemomap);
				}
				else 
				{
					R_LTiStep.LTiStep_LTi_Attributes.high_chemokine_grid_square = -1;
				}
				S_LTi_State_Machine.chemokine_response_probability = Functions.probability_responds_to_chemokine(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.totalchemoLevels, R_LTiStep.LTiStep_LTi_Attributes.chemomap);
				S_LTi_State_Machine.T.SetCounter(0);
				//System.out.println("Resetting Clock T");
			}
	};
public class t5 extends Transition {
		private LTiStep R_LTiStep;
		private LTiController C_LTiController;
		private LTi_State_Machine S_LTi_State_Machine;
			
			
		public 	t5(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
				S_LTi_State_Machine, State src, State tgt)
		{
			super("S_LTi_State_Machine_t5", src, tgt);
			this.R_LTiStep = R_LTiStep;
			this.C_LTiController = C_LTiController;
			this.S_LTi_State_Machine = S_LTi_State_Machine;
			
			// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
		}
				
			public boolean Condition() {
				if (S_LTi_State_Machine.contactedCell_ID != -1 && S_LTi_State_Machine.adhered == true && S_LTi_State_Machine.T.GetCounter() > 0) {
					//System.out.println("Condition of transition S_LTi_State_Machine_t5 is true");
					return true;
				}
				else {
					System.out.println("Condition of transition S_LTi_State_Machine_t5 is false");
					return false;
				}
			}
			public void Action() {
				S_LTi_State_Machine.T.SetCounter(0);
				//System.out.println("Resetting Clock T");
			}
	};
public class t2 extends Transition {
		private LTiStep R_LTiStep;
		private LTiController C_LTiController;
		private LTi_State_Machine S_LTi_State_Machine;
		
		public t2(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine, State src, State tgt)
		{
			super("S_LTi_State_Machine_t2", src, tgt);
			this.R_LTiStep = R_LTiStep;
			this.C_LTiController = C_LTiController;
			this.S_LTi_State_Machine = S_LTi_State_Machine;
		}
		
		public boolean Condition() 
		{
			if (S_LTi_State_Machine.pJunctionValue > (0) && S_LTi_State_Machine.pJunctionValue <= (0 + (1 - S_LTi_State_Machine.chemokine_response_probability))) {
					//System.out.println("Condition of transition S_LTi_State_Machine_t2 is true");
					return true;
			}
			else {
				//System.out.println("Condition of transition S_LTi_State_Machine_t2 is false");
				return false;
			}
		}
		public void Action() {
			S_LTi_State_Machine.T.SetCounter(0);
			//System.out.println("Resetting Clock T");
		}
	};

//0 + 1 - S_LTi_State_Machine.chemokine_response_probability
public class t3 extends Transition {
		private LTiStep R_LTiStep;
		private LTiController C_LTiController;
		private LTi_State_Machine S_LTi_State_Machine;
		
		public t3(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine S_LTi_State_Machine, State src, State tgt)
		{
			super("S_LTi_State_Machine_t3", src, tgt);
			this.R_LTiStep = R_LTiStep;
			this.C_LTiController = C_LTiController;
			this.S_LTi_State_Machine = S_LTi_State_Machine;
		}
		
		public boolean Condition() 
		{
			if (S_LTi_State_Machine.pJunctionValue > (0 + 1 - S_LTi_State_Machine.chemokine_response_probability) && S_LTi_State_Machine.pJunctionValue <= (0 + 1 - S_LTi_State_Machine.chemokine_response_probability + (S_LTi_State_Machine.chemokine_response_probability))) {
					//System.out.println("Condition of transition S_LTi_State_Machine_t3 is true");
					return true;
			}
			else {
				//System.out.println("Condition of transition S_LTi_State_Machine_t3 is false");
				return false;
			}
		}
		public void Action() {
			S_LTi_State_Machine.T.SetCounter(0);
			//System.out.println("Resetting Clock T");
		}
	};

//0 + 1 - S_LTi_State_Machine.chemokine_response_probability + S_LTi_State_Machine.chemokine_response_probability
//0
public class t11 extends Transition {
		private LTiStep R_LTiStep;
		private LTiController C_LTiController;
		private LTi_State_Machine S_LTi_State_Machine;
			
			
		public 	t11(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
				S_LTi_State_Machine, State src, State tgt)
		{
			super("S_LTi_State_Machine_t11", src, tgt);
			this.R_LTiStep = R_LTiStep;
			this.C_LTiController = C_LTiController;
			this.S_LTi_State_Machine = S_LTi_State_Machine;
			
			// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
		}
				
			public boolean Condition() {
				if (S_LTi_State_Machine.contactedCell_ID != -1 && S_LTi_State_Machine.T.GetCounter() > 0) {
					//System.out.println("Condition of transition S_LTi_State_Machine_t11 is true");
					return true;
				}
				else {
					System.out.println("Condition of transition S_LTi_State_Machine_t11 is false");
					return false;
				}
			}
			public void Action() {
				S_LTi_State_Machine.T.SetCounter(0);
				//System.out.println("Resetting Clock T");
			}
	};
public class t7 extends Transition {
		private LTiStep R_LTiStep;
		private LTiController C_LTiController;
		private LTi_State_Machine S_LTi_State_Machine;
			
			
		public 	t7(LTiStep R_LTiStep, LTiController C_LTiController, LTi_State_Machine 
				S_LTi_State_Machine, State src, State tgt)
		{
			super("S_LTi_State_Machine_t7", src, tgt);
			this.R_LTiStep = R_LTiStep;
			this.C_LTiController = C_LTiController;
			this.S_LTi_State_Machine = S_LTi_State_Machine;
			
			// KA: May need to check this if we look at events - not 100% sure transferred correctly from C++
		}
				
			public boolean Condition() {
				if (S_LTi_State_Machine.contactedCell_ID == -1 && S_LTi_State_Machine.T.GetCounter() > 0) {
					//System.out.println("Condition of transition S_LTi_State_Machine_t7 is true");
					return true;
				}
				else {
					System.out.println("Condition of transition S_LTi_State_Machine_t7 is false");
					return false;
				}
			}
			public void Action() {
				R_LTiStep.LTiStep_LTi_Attributes.totalchemoLevels = Functions.measure_chemokine_expression(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.chemomap);
				if (R_LTiStep.LTiStep_LTi_Attributes.totalchemoLevels > 0) 
				{
					R_LTiStep.LTiStep_LTi_Attributes.high_chemokine_grid_square = Functions.calculate_high_grid_square(R_LTiStep.LTiStep_LTi_Attributes.chemomap);
				}
				else 
				{
					R_LTiStep.LTiStep_LTi_Attributes.high_chemokine_grid_square = -1;
				}
				S_LTi_State_Machine.chemokine_response_probability = Functions.probability_responds_to_chemokine(R_LTiStep.LTiStep_LTi_Attributes.LTi_loc, R_LTiStep.LTiStep_LTi_Attributes.totalchemoLevels, R_LTiStep.LTiStep_LTi_Attributes.chemomap);
				S_LTi_State_Machine.T.SetCounter(0);
				//System.out.println("Resetting Clock T");
			}
	};
	
	}
