package autogenerated_sim;

import roboCalcAPI.Controller;

public class LTiController extends Controller {

	private LTiStep R_LTiStep;
	

	public LTiController(LTiStep R_LTiStep)
	{
		this.R_LTiStep = R_LTiStep;
		
	}



	public void Execute() {
			super.Execute();
		}

}

