package autogenerated_sim;

import roboCalcAPI.Controller;

public class LTin_Controller extends Controller {

	private LTin_Step R_LTin_Step;
	

	public LTin_Controller(LTin_Step R_LTin_Step)
	{
		this.R_LTin_Step = R_LTin_Step;
		
	}



	public void Execute() {
			super.Execute();
		}

}

