package autogenerated_sim;

public class LTin_Attributes implements HardwareComponent {
	
	
	public Double2D LTin_loc;
	public double angle_to_move;
	public double cellSpeed;
	public int cell_id;
	public Tracking_Stats tracking;

	
	
	public LTin_Attributes()
	{
		this.LTin_loc = new Double2D();
		this.angle_to_move = 0;
		this.cellSpeed = 0;
		this.cell_id = 0;
		this.tracking = new Tracking_Stats();
	
	}
	
	

	public void Sensors()
	{
		
	}
	public void Actuators()
	{
		
	}



}
