package autogenerated_sim;

public class LTin_Step {
	

	// Objects in Java version, were extended in C++ (but no multiple inheritance in Java)
	public LTin_Attributes LTin_Step_LTin_Attributes;
	public Operations LTin_Step_Operations;

	public LTin_Step()
	{
		this.LTin_Step_LTin_Attributes = new LTin_Attributes();
		this.LTin_Step_Operations = new Operations();
	}
		
		
	public void Sensors() {
		this.LTin_Step_LTin_Attributes.Sensors();
		this.LTin_Step_Operations.Sensors();
	}
	
	public void Actuators() {
		this.LTin_Step_LTin_Attributes.Actuators();
		this.LTin_Step_Operations.Actuators();
	}
	
	


}
		
