package autogenerated_sim;

import sim.engine.SimState;
import sim.engine.Steppable;
import sim.engine.Stoppable;

public class LTin_Module implements Steppable, Stoppable {

	private LTin_Controller LTin_Module_LTin_Controller;
	private LTin_Step LTin_Module_LTin_Step;
	
	// For MASON specific sims, need these attributes
	/**
	 * Flag to show that the LTo has been removed as this did not differentiate by a set time
	 */
	public boolean stopped = false;
		
	// KA: For MASON we need to be able to stop the cell, so the below needs to be added
	/**
	 * Flag to show if this class has been stopped (when no longer needed)
	 */
	public Stoppable stopper = null;
	    
	/**
	 * Method to change the value of the stopper
	 * @param stopper	Whether the class should be stopped or not
	 */
	public void setStopper(Stoppable stopper)   {this.stopper = stopper;}
	    
	/**
	* Method to stop the class where necessary
	*/
	public void stop(){
		stopped = true;
	   	stopper.stop();
	}
	
	/**
	* Getter for robotic platform containing the step
	*/ 
	

	public LTin_Module()
	{
		this.LTin_Module_LTin_Controller = null;
		
		
		// KA: Moved Robotic Platform into constructor, as needs to be initialised before state machine	
	this.LTin_Module_LTin_Step = new LTin_Step ();
		
		}


public LTin_Step getLTin_Module_LTin_Step()
{
	return this.LTin_Module_LTin_Step;
}

	public void Init() {
		this.LTin_Module_LTin_Controller = new LTin_Controller (LTin_Module_LTin_Step);
		LTin_State_Machine LTin_Controller_LTin_State_Machine = new LTin_State_Machine(LTin_Module_LTin_Step, LTin_Module_LTin_Controller);
		LTin_Module_LTin_Controller.stm = LTin_Controller_LTin_State_Machine;
	}

	public void Execute() {
		this.LTin_Module_LTin_Step.Sensors();
		this.LTin_Module_LTin_Controller.Execute();
		this.LTin_Module_LTin_Step.Actuators();
	}

	
	public void step(SimState state)
	{
		// MASON step method. Should call Execute, but may do other operations that need specifying in here
		Execute();
	}
	
	// If outputting the simulation as a GUI, draw function is also required here
	}
