package autogenerated_sim;

public class LTiStep {
	

	// Objects in Java version, were extended in C++ (but no multiple inheritance in Java)
	public LTi_Attributes LTiStep_LTi_Attributes;
	public Operations LTiStep_Operations;

	public LTiStep()
	{
		this.LTiStep_LTi_Attributes = new LTi_Attributes();
		this.LTiStep_Operations = new Operations();
	}
		
		
	public void Sensors() {
		this.LTiStep_LTi_Attributes.Sensors();
		this.LTiStep_Operations.Sensors();
	}
	
	public void Actuators() {
		this.LTiStep_LTi_Attributes.Actuators();
		this.LTiStep_Operations.Actuators();
	}
	
	


}
		
