package autogenerated_sim;

import roboCalcAPI.Controller;

public class LTo_Controller extends Controller {

	private LTo_Step R_LTo_Step;
	

	public LTo_Controller(LTo_Step R_LTo_Step)
	{
		this.R_LTo_Step = R_LTo_Step;
		
	}



	public void Execute() {
			super.Execute();
		}

}

