package autogenerated_sim;

public class LTo_Attributes implements HardwareComponent {
	
	
	public boolean new_LTin_binding;
	public boolean new_LTi_binding;
	public double adhesionExpressed;
	public double chemokineExpressed;
	public Double2D LTo_loc;
	public boolean expressingRET;
	public double maxVCAMProbability;
	public double retLigandTime;
	public boolean maxExpressionReached;
	public double adhesionIncrement;
	public double chemokineDecrement;
	public double chemokineExpressionLimit;
	public int cellDivisionTime;
	public int cell_id;
	public Int2D gridLoc;
	public String entry_state;
	public int lTinContactStateChangeTimePoint;
	public int lTiContactStateChangeTimePoint;

	
	
	public LTo_Attributes()
	{
		this.new_LTin_binding = false;
		this.new_LTi_binding = false;
		this.adhesionExpressed = 0;
		this.chemokineExpressed = 0;
		this.LTo_loc = new Double2D();
		this.expressingRET = false;
		this.maxVCAMProbability = 0;
		this.retLigandTime = 0;
		this.maxExpressionReached = false;
		this.adhesionIncrement = 0.05;
		this.chemokineDecrement = 0.005;
		this.chemokineExpressionLimit = 0;
		this.cellDivisionTime = 0;
		this.cell_id = 0;
		this.gridLoc = new Int2D();
		this.entry_state = "start";
		this.lTinContactStateChangeTimePoint = -1;
		this.lTiContactStateChangeTimePoint = -1;
	
	}
	
	

	public void Sensors()
	{
		
	}
	public void Actuators()
	{
		
	}



}
