package autogenerated_sim;

import sim.engine.SimState;
import sim.engine.Steppable;
import sim.engine.Stoppable;

public class LTo_Module implements Steppable, Stoppable {

	private LTo_Controller LTo_Module_LTo_Controller;
	private LTo_Step LTo_Module_LTo_Step;
	
	// For MASON specific sims, need these attributes
	/**
	 * Flag to show that the LTo has been removed as this did not differentiate by a set time
	 */
	public boolean stopped = false;
		
	// KA: For MASON we need to be able to stop the cell, so the below needs to be added
	/**
	 * Flag to show if this class has been stopped (when no longer needed)
	 */
	public Stoppable stopper = null;
	    
	/**
	 * Method to change the value of the stopper
	 * @param stopper	Whether the class should be stopped or not
	 */
	public void setStopper(Stoppable stopper)   {this.stopper = stopper;}
	    
	/**
	* Method to stop the class where necessary
	*/
	public void stop(){
		stopped = true;
	   	stopper.stop();
	}
	
	/**
	* Getter for robotic platform containing the step
	*/ 
	

	public LTo_Module()
	{
		this.LTo_Module_LTo_Controller = null;
		
		
		// KA: Moved Robotic Platform into constructor, as needs to be initialised before state machine	
	this.LTo_Module_LTo_Step = new LTo_Step ();
		
		}


public LTo_Step getLTo_Module_LTo_Step()
{
	return this.LTo_Module_LTo_Step;
}

	public void Init() {
		this.LTo_Module_LTo_Controller = new LTo_Controller (LTo_Module_LTo_Step);
		LTo_State_Machine LTo_Controller_LTo_State_Machine = new LTo_State_Machine(LTo_Module_LTo_Step, LTo_Module_LTo_Controller);
		LTo_Module_LTo_Controller.stm = LTo_Controller_LTo_State_Machine;
	}

	public void Execute() {
		this.LTo_Module_LTo_Step.Sensors();
		this.LTo_Module_LTo_Controller.Execute();
		this.LTo_Module_LTo_Step.Actuators();
	}

	
	public void step(SimState state)
	{
		// MASON step method. Should call Execute, but may do other operations that need specifying in here
		Execute();
	}
	
	// If outputting the simulation as a GUI, draw function is also required here
	}
