package autogenerated_sim;

public class Operations implements HardwareComponent {
	

	
	
	public Operations()
	{
	
	}
	
	public void update_tracking_stats(Tracking_Stats tracking, int cell_id, Double2D loc, double distanceMoved)
	{}
	public void setPositionOnTract(int cell_id, Double2D cell_loc)
	{}
	public void stop_cell_on_schedule(int cell_id)
	{}
	public void divide_cells(Int2D gridLoc, double adhesionExpressed, double chemokineExpressed, boolean maxExpressionReached, int distance, String entry_state)
	{}
	

	public void Sensors()
	{
		
	}
	public void Actuators()
	{
		
	}



}
