package autogenerated_sim;
	
public class Tracking_Stats {
	public double timeTracked;
	public double trackLength;
	public double trackLengthScaled;
	public double trackedVelocity;
	public Double2D agentTrackStartLocation;
	public Double2D agentTrackEndLocation;
	public Double2D agentPreviousLocation;
}
	

